# -*- coding: utf-8 -*-
"""iris_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aok4PyNNcHMJAdDg5CXpVvy0IASMb80k

# Import necessary libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

"""# Load the dataset from the CSV file"""

file_path = 'iris.csv'
data = pd.read_csv(file_path)

"""# Separate features and target variable"""

X = data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = data['Species']

"""# Encoding"""

y = pd.factorize(y)[0]

"""# Split the dataset into training and testing sets"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

"""# Standardize the features"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""# Train a RandomForestClassifier and Predict"""

clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Training
clf.fit(X_train, y_train)

# Prediction
y_pred = clf.predict(X_test)

"""# Evaluate the model"""

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))